// packages/web-components/src/components/Stack/Stack.ts
import style from "@themeless-ui/style/dist/stack.css?inline";
import { cn } from "@themeless-ui/utils";
import { html, nothing, unsafeCSS } from "lit";
import { customElement, property } from "lit/decorators.js";
import { TUIComponent } from "../TUIComponent";

const stackClassName = cn("stack");
const verticalClassName = cn("stack-vertical");
const horizontalClassName = cn("stack-horizontal");

type Direction = "vertical" | "horizontal";

@customElement("tui-stack")
export class Stack extends TUIComponent {
  /**
   * The direction to stack the elements.
   *
   * @default vertical
   */
  @property()
  direction!: Direction;

  static styles = unsafeCSS(style);

  constructor() {
    super();

    this.direction = "vertical";
  }

  override render() {
    const classNames = [
      stackClassName,
      this.direction === "vertical" ? verticalClassName : horizontalClassName,
    ].join(" ");

    return html`
      <div
        class="${classNames}"
        id="${this.id || nothing}"
        data-testid="${this.testId || nothing}"
      >
        <slot></slot>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "tui-stack": Stack;
  }
}

// packages/react/src/components/Stack/Stack.tsx
import { CommonComponentProps, cn } from "@themeless-ui/utils";
import { ReactNode } from "react";

export type StackProps = {
  /**
   * The direction to stack the elements.
   */
  direction?: "vertical" | "horizontal";

  /**
   * The elements to be stacked.
   */
  children?: ReactNode;
} & CommonComponentProps;

const stackClassName = cn("stack");
const verticalClassName = cn("stack-vertical");
const horizontalClassName = cn("stack-horizontal");

/**
 * Display a stack of items.
 */
export function Stack({
  direction = "vertical",
  children,
  id,
  testId,
}: StackProps) {
  const classNames = [
    stackClassName,
    direction === "vertical" ? verticalClassName : horizontalClassName,
  ].join(" ");

  return (
    <div className={classNames} id={id} data-testid={testId}>
      {children}
    </div>
  );
}
