// packages/react/src/components/Textarea/Textarea.tsx
import { CommonComponentProps, cn } from "@themeless-ui/utils";
import { TextareaHTMLAttributes } from "react";

type HTMLTextareaProps = TextareaHTMLAttributes<HTMLTextAreaElement>;

export type TextareaProps = {
  /**
   * Name of the textarea.
   */
  name?: HTMLTextareaProps["name"];

  /**
   * Prevent the user from interacting with the textarea.
   */
  disabled?: HTMLTextareaProps["disabled"];

  /**
   * Indicates that the user should not be able to edit the value of the textarea.
   */
  readOnly?: HTMLTextareaProps["readOnly"];

  /**
   * Indicates that the user must specify a value for the textarea before the owning form can be submitted.
   */
  required?: HTMLTextareaProps["required"];

  /**
   * Brief hint for the user as to what kind of information is expected in the textarea.
   */
  placeholder?: HTMLTextareaProps["placeholder"];

  /**
   * The value of the textarea.
   * Use only when using the textarea as controlled component (state handled by React).
   */
  value?: HTMLTextareaProps["value"];

  /**
   * Callback to call when the textarea's value is modified.
   */
  onChange?: HTMLTextareaProps["onChange"];

  /**
   * Callback to call when the textarea is clicked.
   */
  onClick?: HTMLTextareaProps["onClick"];

  /**
   * Callback to call when the textarea receives focus.
   */
  onFocus?: HTMLTextareaProps["onFocus"];

  /**
   * Callback to call when the textarea loses focus.
   */
  onBlur?: HTMLTextareaProps["onBlur"];
} & CommonComponentProps;

const className = cn("textarea");

/**
 * Display an textarea.
 */
export function Textarea({
  name,
  disabled,
  readOnly,
  required,
  placeholder,
  value,
  onChange,
  onClick,
  onFocus,
  onBlur,
  id,
  testId,
}: TextareaProps) {
  return (
    <textarea
      name={name}
      disabled={disabled}
      readOnly={readOnly}
      required={required}
      placeholder={placeholder}
      value={value}
      onChange={onChange}
      onClick={onClick}
      onFocus={onFocus}
      onBlur={onBlur}
      className={className}
      id={id}
      data-testid={testId}
    />
  );
}

// packages/web-components/src/components/Textarea/Textarea.ts
import style from "@themeless-ui/style/dist/textarea.css?inline";
import { cn } from "@themeless-ui/utils";
import { html, nothing, unsafeCSS } from "lit";
import { customElement, property } from "lit/decorators.js";
import {
  TUIBlurEvent,
  TUIChangeEvent,
  TUIClickEvent,
  TUIFocusEvent,
  TUIMouseEnterEvent,
  TUIMouseLeaveEvent,
  TUITouchEndEvent,
  TUITouchStartEvent,
} from "../../events";
import { TUIComponent } from "../TUIComponent";

const className = cn("textarea");

@customElement("tui-textarea")
export class Textarea extends TUIComponent {
  /**
   * Name of the textarea.
   */
  @property()
  name?: HTMLTextAreaElement["name"];

  /**
   * Prevent the user from interacting with the textarea.
   */
  @property({ type: Boolean })
  disabled?: HTMLTextAreaElement["disabled"];

  /**
   * Indicates that the user should not be able to edit the value of the textarea.
   */
  @property({ type: Boolean })
  readOnly?: HTMLTextAreaElement["readOnly"];

  /**
   * Indicates that the user must specify a value for the textarea before the owning form can be submitted.
   */
  @property({ type: Boolean })
  required?: HTMLTextAreaElement["required"];

  /**
   * Brief hint for the user as to what kind of information is expected in the textarea.
   */
  @property()
  placeholder?: HTMLTextAreaElement["placeholder"];

  /**
   * The value of the textarea.
   * Use only when using the textarea as controlled component (state handled by React).
   */
  @property()
  value?: HTMLTextAreaElement["value"];

  private _handleChange() {
    this.dispatchEvent(new TUIChangeEvent());
  }

  private _handleClick() {
    this.dispatchEvent(new TUIClickEvent());
  }

  private _handleFocus() {
    this.dispatchEvent(new TUIFocusEvent());
  }
  private _handleBlur() {
    this.dispatchEvent(new TUIBlurEvent());
  }

  private _handleMouseEnter() {
    this.dispatchEvent(new TUIMouseEnterEvent());
  }

  private _handleMouseLeave() {
    this.dispatchEvent(new TUIMouseLeaveEvent());
  }

  private _handleTouchStart() {
    this.dispatchEvent(new TUITouchStartEvent());
  }

  private _handleTouchEnd() {
    this.dispatchEvent(new TUITouchEndEvent());
  }

  static styles = unsafeCSS(style);

  override render() {
    return html`
      <textarea
        name="${this.name || nothing}"
        placeholder="${this.placeholder || nothing}"
        value="${this.value || nothing}"
        ?disabled="${this.disabled}"
        ?readOnly="${this.readOnly}"
        ?required="${this.required}"
        @change="${this._handleChange}"
        @click="${this._handleClick}"
        @focus="${this._handleFocus}"
        @blur="${this._handleBlur}"
        @mouseEnter="${this._handleMouseEnter}"
        @mouseLeave="${this._handleMouseLeave}"
        @touchStart="${this._handleTouchStart}"
        @touchEnd="${this._handleTouchEnd}"
        class="${className}"
        id="${this.id || nothing}"
        data-testid="${this.testId || nothing}"
      ></textarea>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "tui-textarea": Textarea;
  }
}
